language: go

services:
  - docker

go:
  - 1.15

before_install:
  - docker build . -t compressor
  - go get github.com/mattn/goveralls

script:
  # - set -e
  # - ls
  - go test
  - $GOPATH/bin/goveralls -service=travis-ci
  # - $GOPATH/bin/goveralls --help
  # - $GOPATH/bin/goveralls -repotoken $COVERALLS_TOKEN
  - docker run --cidfile="machine.id" -it compressor ./main benchmark -generate -algorithm=lzss,dmc,huffman,flate,gzip,lzw,zlib,arithmetic,[lzss,huffman],[lzss,arithmetic],[arithmetic,huffman] alice29.txt,asyoulik.txt,cp.html,fields.c,grammar.lsp,kennedy.xls,lcet10.txt,plrabn12.txt,ptt5,sum,xargs.1
  - docker cp $(cat machine.id):/go/src/github.com/mrfleap/custom-compression/index.html ./index.html
  - rm machine.id

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
