language: minimal

services:
  - docker

before_install:
  - docker build . -t compressor

script:
  - docker run -it compressor ./main benchmark -generate alice29.txt,asyoulik.txt
  # - docker run -it compressor ./main benchmark all cp.html
  # - docker run -it compressor ./main benchmark all fields.c
  # - docker run -it compressor ./main benchmark all grammar.lsp
  # - docker run -it compressor ./main benchmark all kennedy.xls
  # - docker run -it compressor ./main benchmark all lcet10.txt
  # - docker run -it compressor ./main benchmark all plrabn12.txt
  # - docker run -it compressor ./main benchmark all ptt5
  # - docker run -it compressor ./main benchmark all sum
  # - docker run -it compressor ./main benchmark all xargs.1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
