language: go

go:
  - master

services:
  - docker

before_install:
  - docker build . -t compressor

script:
  - docker run -it compressor ./main benchmark lzss rows.json
  - docker run -it compressor ./main benchmark lzss boundaries.zip
  - docker run -it compressor ./main benchmark lzss sales.pdf
